spring.application.name=place

# ?? ??? ?? ?? ?? (???? ?? ?? ?? place_server.log ??? ????)
logging.file.name=place_server.log

# ?? ?? ?? (??? System.out.println ? ?? ? ???? ??? ???)
logging.level.root=INFO
logging.level.com.example.place=DEBUG

# ??? ??? ??? ? ?? ?? ?? ??? ?? ???? ??
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7